parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Adapter\Framework\Http\Controller\:
        resource: '../src/Adapter/Framework/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Adapter\Framework\Listener\JsonTransformerExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

    App\Adapter\Framework\Security\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\Adapter\Database\ORM\Doctrine\EventSubscriber\UserEventSubscriber:
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }

    App\Adapter\Database\ORM\Doctrine\EventListener\EntityEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'prePersist'   # this is the only required option for the lifecycle listener tag
              priority: 500
              connection: 'default'
